"""
Example Playwright test file generated by the test generator.
This is a sample template showing the expected format of generated tests.
"""

from playwright.sync_api import Page, expect


def test_example_login_scenario(page: Page) -> None:
    """
    Example pytest-playwright test demonstrating the expected structure.

    This template shows:
    - Explicit page fixture injection
    - Proper locator strategies (data-testid, CSS, text)
    - Comprehensive assertions with error messages
    """
    page.goto("https://example-app.com/login")

    # Locate and fill login form
    email_field = page.locator('[data-testid="email-input"]')
    email_field.fill("testuser@example.com")

    password_field = page.locator('[data-testid="password-input"]')
    password_field.fill("securePassword123!")

    # Locate and click login button
    login_button = page.locator('[data-testid="login-button"]')
    login_button.click()

    # Verify successful login - check for user dashboard elements
    dashboard_heading = page.locator('[data-testid="dashboard-heading"]')
    expect(dashboard_heading).to_be_visible()

    # Verify user name is displayed
    user_greeting = page.locator('[data-testid="user-greeting"]')
    expect(user_greeting).to_have_text("Welcome, testuser@example.com")
