from playwright.sync_api import Page, expect
from src.browser_utils import dismiss_consent_overlays
import pytest

@pytest.mark.evidence(condition_ref="TC-01", story_ref="S01")
def test_01_login(page, evidence_tracker):
    evidence_tracker.navigate('https://www.saucedemo.com')
    dismiss_consent_overlays(page)
    evidence_tracker.fill('#user-name', 'standard_user', label='username input')
    evidence_tracker.fill('#password', 'secret_sauce', label='password input')
    evidence_tracker.click('#login-button', label='login button')
    evidence_tracker.assert_visible('#inventory_sidebar_link', label='inventory items visible')

@pytest.mark.evidence(condition_ref="TC-02", story_ref="S01")
def test_02_add_item_to_cart(page, evidence_tracker):
    evidence_tracker.navigate('https://www.saucedemo.com')
    dismiss_consent_overlays(page)
    evidence_tracker.fill('#user-name', 'standard_user', label='username input')
    evidence_tracker.fill('#password', 'secret_sauce', label='password input')
    evidence_tracker.click('#login-button', label='login button')
    evidence_tracker.click('#add-to-cart-sauce-labs-backpack', label='Sauce Labs Backpack add to cart button')
    evidence_tracker.assert_visible('.shopping_cart_link[data-test="shopping-cart-link"]', label='cart badge updated')

@pytest.mark.evidence(condition_ref="TC-03", story_ref="S01")
def test_03_navigate_to_cart(page, evidence_tracker):
    pytest.skip("Skipping: unresolved placeholders for: 'shopping cart icon'")
    evidence_tracker.navigate('https://www.saucedemo.com')
    dismiss_consent_overlays(page)
    evidence_tracker.fill('#user-name', 'standard_user', label='username input')
    evidence_tracker.fill('#password', 'secret_sauce', label='password input')
    evidence_tracker.click('#login-button', label='login button')
    evidence_tracker.click('#add-to-cart-sauce-labs-backpack', label='Sauce Labs Backpack add to cart button')
    pytest.skip("Unresolved placeholder: {{CLICK:shopping cart icon}}")
    evidence_tracker.navigate('https://www.saucedemo.com/cart.html')
    dismiss_consent_overlays(page)
    evidence_tracker.assert_visible('#continue-shopping', label='shopping cart header visible')

@pytest.mark.evidence(condition_ref="TC-04", story_ref="S01")
def test_04_verify_item_in_cart(page, evidence_tracker):
    pytest.skip("Skipping: unresolved placeholders for: 'shopping cart icon'; 'Sauce Labs Backpack item details visible'")
    evidence_tracker.navigate('https://www.saucedemo.com')
    dismiss_consent_overlays(page)
    evidence_tracker.fill('#user-name', 'standard_user', label='username input')
    evidence_tracker.fill('#password', 'secret_sauce', label='password input')
    evidence_tracker.click('#login-button', label='login button')
    evidence_tracker.click('#add-to-cart-sauce-labs-backpack', label='Sauce Labs Backpack add to cart button')
    pytest.skip("Unresolved placeholder: {{CLICK:shopping cart icon}}")
    evidence_tracker.navigate('https://www.saucedemo.com/cart.html')
    dismiss_consent_overlays(page)
    pytest.skip("Unresolved placeholder: {{ASSERT:Sauce Labs Backpack item details visible}}")

@pytest.mark.evidence(condition_ref="TC-05", story_ref="S01")
def test_05_navigate_to_checkout(page, evidence_tracker):
    pytest.skip("Skipping: unresolved placeholders for: 'shopping cart icon'; 'checkout information form visible'")
    evidence_tracker.navigate('https://www.saucedemo.com')
    dismiss_consent_overlays(page)
    evidence_tracker.fill('#user-name', 'standard_user', label='username input')
    evidence_tracker.fill('#password', 'secret_sauce', label='password input')
    evidence_tracker.click('#login-button', label='login button')
    evidence_tracker.click('#add-to-cart-sauce-labs-backpack', label='Sauce Labs Backpack add to cart button')
    pytest.skip("Unresolved placeholder: {{CLICK:shopping cart icon}}")
    evidence_tracker.navigate('https://www.saucedemo.com/cart.html')
    dismiss_consent_overlays(page)
    evidence_tracker.click('#checkout', label='checkout button')
    evidence_tracker.navigate('https://www.saucedemo.com/checkout')
    dismiss_consent_overlays(page)
    pytest.skip("Unresolved placeholder: {{ASSERT:checkout information form visible}}")

@pytest.mark.evidence(condition_ref="TC-06", story_ref="S01")
def test_06_complete_checkout(page, evidence_tracker):
    pytest.skip("Skipping: unresolved placeholders for: 'shopping cart icon'; 'finish button'")
    evidence_tracker.navigate('https://www.saucedemo.com')
    dismiss_consent_overlays(page)
    evidence_tracker.fill('#user-name', 'standard_user', label='username input')
    evidence_tracker.fill('#password', 'secret_sauce', label='password input')
    evidence_tracker.click('#login-button', label='login button')
    evidence_tracker.click('#add-to-cart-sauce-labs-backpack', label='Sauce Labs Backpack add to cart button')
    pytest.skip("Unresolved placeholder: {{CLICK:shopping cart icon}}")
    evidence_tracker.navigate('https://www.saucedemo.com/cart.html')
    dismiss_consent_overlays(page)
    evidence_tracker.click('#checkout', label='checkout button')
    evidence_tracker.navigate('https://www.saucedemo.com/checkout')
    dismiss_consent_overlays(page)
    evidence_tracker.fill('#user-name', 'John', label='first name input')
    evidence_tracker.fill('#user-name', 'Doe', label='last name input')
    evidence_tracker.fill('#user-name', '12345', label='zip code input')
    pytest.skip("Unresolved placeholder: {{CLICK:finish button}}")
    evidence_tracker.navigate('https://www.saucedemo.com/checkout')
    dismiss_consent_overlays(page)
    evidence_tracker.assert_visible('#login-button', label='Thank You message visible')