#!/usr/bin/env python3
"""Guard: the committed landing images must match the sources they render from.

The landing page's share card (``og-card.png``), its two preview screenshots,
the favicon/icon set and the install/licence PDF are *generated* artefacts.
``scripts/maintenance/make_landing_assets.py`` renders them from
``landing/index.html``, ``landing/tailwind.css``, ``landing/logo_transparent.png``
and ``docs/implementation/tancat-pro-install-and-licence.html``.

Those renders are real captures, so after a copy edit they silently keep
showing the old wording until someone reruns the generator. That happened once:
the air-gap wording change left the old badge in ``og:image`` and only a
reviewer caught it.

The generator writes ``landing/asset-sources.json`` -- the git blob hash of
every source and of the generator itself, plus which assets depend on which
sources. This script recomputes those hashes and fails when a source changed
without a regeneration. It has no Python dependencies (no browser, no Pillow,
no network) and needs only ``git`` on PATH, so it runs as a fast blocking CI
gate and as a pre-commit hook.

It deliberately does NOT re-render. Browser captures are not byte-reproducible
across machines (OS font rasterisation, network webfonts) and the Chromium PDF
embeds a creation timestamp, so a render-and-diff gate would flake on the
Linux CI runner. The source fingerprint is the lightest guard that still
catches the drift that shipped.

Usage:
    python scripts/maintenance/landing_assets_guard.py --check
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence

__all__ = ["MANIFEST", "REPO_ROOT", "check", "git_blob_hash", "main", "write_manifest"]

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST = REPO_ROOT / "landing" / "asset-sources.json"

#: The only hash algorithm this manifest format uses. Git's own blob hashing
#: normalises line endings through the repo's attributes, so a Windows checkout
#: (CRLF) and the Linux CI checkout (LF) agree on a text source's digest.
HASH_ALGO = "git-blob-sha1"

_MANIFEST_COMMENT = (
    "Generated by scripts/maintenance/make_landing_assets.py - do not edit by hand. "
    "Run the generator after any landing/install source change."
)


def git_blob_hash(path: Path) -> str:
    """Return the git blob hash of *path*, with the repo's filters applied.

    Git applies ``core.autocrlf``/``.gitattributes`` to a text file before it
    hashes it, so the digest is the same on a CRLF Windows checkout and an LF
    Linux checkout. That is what makes this guard portable.
    """
    try:
        result = subprocess.run(
            ["git", "hash-object", "--", str(path)],
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError as exc:
        raise RuntimeError("git is required on PATH to hash landing sources") from exc
    if result.returncode != 0:
        raise RuntimeError(f"git hash-object failed for {path}: {result.stderr.strip()}")
    return result.stdout.strip()


def write_manifest(
    asset_sources: Mapping[str, Sequence[str]],
    *,
    generator_path: Path,
    manifest_path: Path = MANIFEST,
    repo_root: Path = REPO_ROOT,
) -> Path:
    """Write the source fingerprint for the generated landing assets.

    *asset_sources* maps a landing file name (e.g. ``"og-card.png"``) to the
    repo-relative source paths that determine it. Called by the generator after
    it has re-rendered, so the manifest always describes the committed assets.
    """
    generator_rel = generator_path.resolve().relative_to(repo_root.resolve()).as_posix()
    sources: dict[str, str] = {}
    assets: dict[str, list[str]] = {}
    for name, source_list in asset_sources.items():
        asset_rel = f"landing/{name}"
        assets[asset_rel] = list(source_list)
        for source in source_list:
            sources.setdefault(source, git_blob_hash(repo_root / source))

    manifest = {
        "comment": _MANIFEST_COMMENT,
        "generator": generator_rel,
        "generator_hash": git_blob_hash(generator_path),
        "hash": HASH_ALGO,
        "assets": assets,
        "sources": sources,
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest_path


def check(manifest_path: Path = MANIFEST, repo_root: Path = REPO_ROOT) -> list[str]:
    """Return the list of drift problems; an empty list means the assets are current."""
    repo_root = repo_root.resolve()
    if not manifest_path.exists():
        return [
            f"missing manifest {manifest_path} - run scripts/maintenance/make_landing_assets.py",
        ]
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return [f"manifest {manifest_path} is not valid JSON: {exc}"]

    problems: list[str] = []
    if manifest.get("hash") != HASH_ALGO:
        problems.append(
            f"manifest uses unknown hash {manifest.get('hash')!r} (expected {HASH_ALGO!r})",
        )

    assets: dict[str, list[str]] = manifest.get("assets") or {}
    for rel, expected in (manifest.get("sources") or {}).items():
        path = repo_root / rel
        if not path.exists():
            problems.append(f"source {rel} is missing")
            continue
        if git_blob_hash(path) != expected:
            dependents = sorted(a for a, srcs in assets.items() if rel in srcs)
            suffix = f" (affects {', '.join(dependents)})" if dependents else ""
            problems.append(f"{rel} changed since the assets were generated{suffix}")

    generator_rel = manifest.get("generator")
    if generator_rel:
        generator_path = repo_root / generator_rel
        if not generator_path.exists():
            problems.append(f"generator {generator_rel} is missing")
        elif git_blob_hash(generator_path) != manifest.get("generator_hash"):
            problems.append(f"{generator_rel} changed since the assets were generated")

    for rel in assets:
        path = repo_root / rel
        if not path.exists():
            problems.append(f"asset {rel} is missing")
        elif path.stat().st_size == 0:
            problems.append(f"asset {rel} is empty")

    return problems


def main() -> int:
    """Run the guard; 0 = assets current, 1 = drift, 2 = bad usage."""
    if "--check" not in sys.argv[1:]:
        print("usage: python scripts/maintenance/landing_assets_guard.py --check")
        return 2

    problems = check()
    if problems:
        print("FAIL: landing assets are out of date with their sources:")
        for problem in problems:
            print(f"  - {problem}")
        print()
        print("Fix: python scripts/maintenance/make_landing_assets.py")
        print("     then commit the regenerated assets and landing/asset-sources.json.")
        return 1

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    print(
        f"OK: landing assets match {len(manifest.get('sources', {}))} source(s) "
        f"across {len(manifest.get('assets', {}))} asset(s).",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
