"""Code cleanup and skip-insertion helpers for placeholder resolution.

Extracted from ``placeholder_orchestrator.py``. Handles removing raw
placeholder lines, old per-placeholder skip lines, and inserting
consolidated pytest.skip() calls at the top of test functions when
placeholders cannot be resolved.
"""

from __future__ import annotations

import re

from src.pipeline_models import TestJourney


def remove_old_placeholder_skips(
    lines: list[str],
    journeys: list[TestJourney],
) -> list[str]:
    """Filter out old per-placeholder skip lines generated by code_normalizer.

    Removes lines like:
    - pytest.skip('Unresolved placeholder in this step. {{CLICK:...}}')
    - pytest.skip('{{ASSERT:Product categories are visible}}')
    - pytest.skip("{{CLICK:Proceed to checkout button}}")

    These are left over when the orchestrator fails to resolve a placeholder
    and code_normalizer replaces the raw token with a pytest.skip() call.
    The consolidated skip inserted by insert_consolidated_skips() replaces these.
    """
    raw_placeholder_skip_re = re.compile(r"""pytest\.skip\(\s*['"]\{\{[A-Z_]+:.*?\}\}['"]\s*\)""")
    unresolved_skip_re = re.compile(
        r"""pytest\.skip\(\s*['"]Unresolved placeholder in this step\.\s*\{\{.*?\}\}['"]\s*\)"""
    )
    raw_placeholder_in_skip_re = re.compile(r"""pytest\.skip\(\s*['"].*?\{\{[A-Z_]+:.*?\}\}.*?['"]\s*\)""")
    result_lines: list[str] = []

    for line in lines:
        stripped = line.strip()
        if raw_placeholder_skip_re.match(stripped):
            continue
        if unresolved_skip_re.match(stripped):
            continue
        if raw_placeholder_in_skip_re.match(stripped):
            continue
        result_lines.append(line)

    return result_lines


def remove_raw_placeholder_lines(lines: list[str]) -> list[str]:
    """Remove any remaining raw {{ACTION:description}} placeholder lines.

    After resolution, any surviving raw placeholder tokens are covered by
    the consolidated skip at the test top. Removing them prevents
    code_normalizer from converting them into additional pytest.skip()
    lines later in the pipeline.

    R-002 FIX: Also removes placeholder tokens embedded in comments,
    prose lines, or any non-statement context.
    """
    raw_placeholder_re = re.compile(r"^\s*\{\{[A-Z_]+:.*?\}\}\s*$")
    embedded_placeholder_re = re.compile(r"\{\{[A-Z_]+:[^}]+\}\}")

    result_lines: list[str] = []

    for line in lines:
        if raw_placeholder_re.match(line):
            continue

        stripped = line.strip()
        if stripped.startswith("#") and embedded_placeholder_re.search(stripped):
            continue

        if embedded_placeholder_re.search(stripped):
            code_patterns = [
                r"^\s*def\s+",
                r"^\s*import\s+",
                r"^\s*from\s+",
                r"^\s*class\s+",
                r"^\s*@",
                r"^\s*\w+\s*=\s*",
                r"^\s*evidence_tracker\.",
                r"^\s*page\.",
                r"^\s*pytest\.",
                r"^\s*dismiss_consent",
            ]
            is_code = any(re.match(p, line) for p in code_patterns)
            if not is_code:
                continue

        result_lines.append(line)

    return result_lines


def insert_consolidated_skips(
    lines: list[str],
    journeys: list[TestJourney],
    journey_unresolved: dict[str, list[str]],
    original_lines: list[str],
) -> list[str]:
    """Insert a single consolidated pytest.skip() at the start of each test with unresolved placeholders.

    The skip is placed AFTER any consent-dismiss or POM-instantiation lines,
    so that dismiss_consent_overlays(page) still runs before the skip.
    """
    skip_messages: dict[str, str] = {}
    for test_name, unresolved_list in journey_unresolved.items():
        if unresolved_list:
            seen: set[str] = set()
            unique_unresolved: list[str] = []
            for desc in unresolved_list:
                if desc not in seen:
                    seen.add(desc)
                    unique_unresolved.append(desc)
            skip_messages[test_name] = "Skipping: unresolved placeholders for: " + "; ".join(
                f"'{desc}'" for desc in unique_unresolved
            )

    if not skip_messages:
        return lines

    result_lines: list[str] = []
    inserted_for: set[str] = set()

    for index, line in enumerate(lines):
        result_lines.append(line)
        stripped = line.strip()
        if stripped.startswith("def test_") and "(" in stripped and ":" in stripped:
            test_name = stripped.split("(")[0].replace("def ", "").strip()
            if test_name in skip_messages and test_name not in inserted_for:
                next_line = lines[index + 1].strip() if index + 1 < len(lines) else ""
                if next_line.startswith("pytest.skip(") or next_line.startswith("@"):
                    continue

                indent = "    "
                skip_line = f"{indent}pytest.skip({skip_messages[test_name]!r})"

                insert_after = index
                for scan_idx in range(index + 1, min(index + 15, len(lines))):
                    scan_stripped = lines[scan_idx].strip()
                    if "pytest.skip(" in scan_stripped:
                        inserted_for.add(test_name)
                        break
                    if "dismiss_consent_overlays(" in scan_stripped and not scan_stripped.startswith("pytest."):
                        insert_after = scan_idx

                if test_name not in inserted_for:
                    indent_line = (
                        " " * (len(lines[insert_after]) - len(lines[insert_after].lstrip()))
                        if insert_after > index
                        else indent
                    )
                    result_lines.append(f"{indent_line}{skip_line.strip()}")
                    inserted_for.add(test_name)

    return result_lines


__all__ = [
    "insert_consolidated_skips",
    "remove_old_placeholder_skips",
    "remove_raw_placeholder_lines",
]
